### ISSUE TITLE
流程能否跑通

### ISSUE THREAD

**Issue by Olivert007** [DavinciEvans/chatGPT-Summary-Bilibili-To-Notion#1]
你好，根据你的代码，试着换成自己的aki_key,报出这样的错？播放视频是中文，个人设置里打开了CC字幕
`Traceback (most recent call last):
  File "/mnt/e/github/opencv/chatGPT-Summary-Bilibili-To-Notion/main.py", line 43, in <module>
    subtitle = BiliSubtitleDownloader(bv_id, p_num, cookie).download_subtitle()
  File "/mnt/e/github/opencv/chatGPT-Summary-Bilibili-To-Notion/bili_subtitle_downloader/bili_subtitle_downloader.py", line 64, in download_subtitle
    subtitle_list = self._get_subtitle(self._get_player_list()[self.p_num])
  File "/mnt/e/github/opencv/chatGPT-Summary-Bilibili-To-Notion/bili_subtitle_downloader/bili_subtitle_downloader.py", line 53, in _get_subtitle
    raise SubtitleDownloadError("字幕下载失败，请确保原视频有cc字幕并更换新的cookie")
bili_subtitle_downloader.bili_subtitle_downloader.SubtitleDownloadError: 字幕下载失败，请确保原视频有cc字幕并更换新的cookie`

**Comment by DavinciEvans** [comment]
不是在个人设置里打开CC字幕哦，而是原视频本身就配有字幕或是b站有自动生成的字幕，是否有字幕可以在视频右下角字幕按钮来查看

如果还有问题，请附上原视频的BV号哦

**Comment by Olivert007** [comment]
视频BV号：BV1Gp4y1h7gQ
视频链接：https://www.bilibili.com/video/BV1Gp4y1h7gQ/，检查多次，原视频没有字母按钮
能否加个微信

**Comment by DavinciEvans** [comment]
没有字幕按钮那就是没有字幕，这样的视频是没有办法生成概要的
